repos:
  # Versioning: Commit messages & changelog
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.15.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Lint / autoformat: Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.2.2"
    hooks:
      # Run the linter
      - id: ruff
        files: ^src/backend/(?:.*/)*.*$
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter
      - id: ruff-format
        files: ^src/backend/(?:.*/)*.*$

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args:
          [
            --ignore-unknown,
            --no-error-on-unmatched-pattern,
            "!chart/**",
            "!CHANGELOG.md",
            "!CONTRIBUTING.md",
            "!LICENSE.md",
            "!src/frontend/pnpm-lock.yaml",
          ]

  # # Lint: Dockerfile (disabled until binary is bundled)
  # - repo: https://github.com/hadolint/hadolint.git
  #   rev: v2.12.1-beta
  #   hooks:
  #     - id: hadolint
  #       args:
  #         [
  #           "--ignore=DL3008",
  #           "--ignore=DL3013",
  #           "--ignore=DL3018",
  #           "--ignore=DL3059",
  #         ]

  # Lint: Bash scripts
  - repo: https://github.com/openstack-dev/bashate.git
    rev: 2.1.1
    hooks:
      - id: bashate
        files: ^(?!.*(?:^|/)contrib(?:/|$)).*$

  # Lint: Shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        files: ^(?!.*(?:^|/)contrib(?:/|$)).*$
        args: ["-x", "--exclude=SC2317,SC2188,SC2143"]

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args:
          [
            --fix,
            --disable,
            MD033,
            --ignore,
            LICENSE.md,
            --ignore,
            CHANGELOG.md,
            --ignore,
            .github,
          ]
