# Copyright (c) 2022, 2023 Humanitarian OpenStreetMap Team
#
# This file is part of FMTM.
#
#     FMTM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     FMTM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with FMTM.  If not, see <https:#www.gnu.org/licenses/>.
#

[project]
name = "fmtm"
dynamic = ["version"]
description = "Field mapping tasking manager"
authors = [
    {name = "HOTOSM", email = "sysadmin@hotosm.org"},
]
dependencies = [
    "uvicorn==0.24.0",
    "fastapi==0.104.1",
    "pydantic==2.5.2",
    "pydantic-settings==2.1.0",
    "geojson-pydantic==1.0.1",
    "python-multipart==0.0.6",
    "sqlalchemy==2.0.23",
    "SQLAlchemy-Utils==0.41.1",
    "psycopg2==2.9.9",
    "geoalchemy2==0.14.2",
    "geojson==3.1.0",
    "shapely==2.0.2",
    "pyxform==1.12.2",
    "sentry-sdk==1.38.0",
    "py-cpuinfo==9.0.0",
    "loguru==0.7.2",
    "minio==7.2.0",
    "pyproj==3.6.1",
    "asgiref==3.7.2",
    "sozipfile==0.3.2",
    "cryptography>=42.0.1",
    "defusedxml>=0.7.1",
    "osm-login-python==1.0.1",
    "osm-fieldwork==0.5.2",
    "osm-rawdata==0.2.3",
    "fmtm-splitter==1.1.2",
]
requires-python = ">=3.10"
readme = "../../README.md"
license = {text = "GPL-3.0-only"}

[build-system]
requires = ["pdm-pep517==1.1.4"]
build-backend = "pdm.pep517.api"

[tool.pdm]
source-includes = ["../../CHANGELOG.md", "../../LICENSE", "../../README.md"]
version = {from = "app/__version__.py"}
[tool.pdm.dev-dependencies]
dev = [
    "pre-commit>=3.5.0",
    "black>=23.11.0",
    "commitizen>=3.13.0",
]
test = [
    "pytest==7.4.3",
    "httpx==0.25.2",
    "pytest-asyncio==0.23.2",
    "pyinstrument==4.6.1",
    "coverage>=7.4.0",
    "coverage-badge>=1.1.0",
]
debug = [
    "ipdb>=0.13.13",
    "debugpy>=1.8.0",
]
docs = [
    "mkdocs==1.5.3",
    "mkdocs-material==9.4.14",
    "mkdocstrings-python==1.7.5",
    "mkdocs-exclude==1.0.2",
    "python-dotenv==1.0.0",
    "mkdocs-git-revision-date-localized-plugin>=1.2.2",
    "mdx-truly-sane-lists>=1.3",
]

[tool.black]
line-length = 88
target-versions = ["py310", "py311"]

[tool.ruff]
target-version = "py310"
line-length = 88
select = ["I", "E", "W", "D", "B", "F", "N", "Q"]
ignore = ["N805", "B008"]
exclude = [
    ".ruff_cache",
    "__pypackages__",
    "app/__version__.py",
]
[tool.ruff.pydocstyle]
convention = "google"
[tool.ruff.flake8-bugbear]
extend-immutable-calls = [
    "fastapi.Depends",
    "fastapi.params.Depends",
    "fastapi.Query",
    "fastapi.params.Query",
    "fastapi.File",
    "fastapi.Security",
]

[tool.pyright]
extraPaths = ["__pypackages__/3.10/lib/"]

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = [
    "tests",
]
asyncio_mode="auto"

[tool.commitizen]
name = "cz_conventional_commits"
version = "2024.0.0"
version_files = [
    "pyproject.toml:version",
    "app/__version__.py",
    "../frontend/package.json:version",
]
changelog_file = "../../CHANGELOG.md"
update_changelog_on_bump = true
